export function isPortalPreview() {
  return process.env.NEXT_PUBLIC_JOB_PORTAL_PREVIEW === 'true';
}

export const PREVIEW_USER = {
  email: 'preview@employer.local',
  role: 'employer',
};

export const PREVIEW_CATEGORIES = [
  { id: 'cat-eng', name: 'Engineering' },
  { id: 'cat-mkt', name: 'Marketing' },
];

const now = Date.now();
const daysAgo = (d) => new Date(now - d * 24 * 60 * 60 * 1000).toISOString();

export const PREVIEW_JOBS = [
  {
    id: 'preview-job-1',
    title: 'Senior Backend Engineer',
    department: 'Engineering',
    location: 'Remote, Ghana',
    status: 'published',
    publishedAt: daysAgo(30),
    description: 'Build scalable APIs and platform services for our product suite.',
    requirements: '5+ years backend experience, Go or Node.js, distributed systems.',
    remoteType: 'remote',
    employmentType: 'full_time',
    salaryMin: 80000,
    salaryMax: 120000,
    currency: 'USD',
    categoryId: 'cat-eng',
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
    screeningQuestions: [
      {
        id: 'sq_years',
        label: 'Years of backend experience',
        type: 'single',
        filterable: true,
        options: ['0–2', '3–5', '6–10', '10+'],
      },
      {
        id: 'sq_stack',
        label: 'Primary stack',
        type: 'multi',
        filterable: true,
        options: ['Go', 'Node.js', 'Python', 'Java'],
      },
    ],
  },
  {
    id: 'preview-job-2',
    title: 'AI Engineer',
    department: 'Engineering',
    location: 'Remote, Europe',
    status: 'published',
    publishedAt: daysAgo(20),
    description: 'Ship production ML features with clear evaluation and monitoring.',
    requirements: 'Python, PyTorch or TensorFlow, MLOps experience.',
    remoteType: 'remote',
    employmentType: 'full_time',
    salaryMin: 90000,
    salaryMax: 140000,
    currency: 'USD',
    categoryId: 'cat-eng',
    createdAt: daysAgo(25),
    updatedAt: daysAgo(5),
  },
  {
    id: 'preview-job-3',
    title: 'Product Marketing Manager',
    department: 'Marketing',
    location: 'Hybrid, Accra',
    status: 'draft',
    publishedAt: null,
    description: 'Own go-to-market for new product launches.',
    requirements: 'B2B SaaS marketing, positioning, content strategy.',
    remoteType: 'hybrid',
    employmentType: 'full_time',
    salaryMin: 60000,
    salaryMax: 90000,
    currency: 'USD',
    categoryId: 'cat-mkt',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
  },
  {
    id: 'preview-job-4',
    title: 'DevOps Engineer',
    department: 'Engineering',
    location: 'Remote',
    status: 'closed',
    publishedAt: daysAgo(90),
    description: 'Maintain CI/CD pipelines and cloud infrastructure.',
    requirements: 'Kubernetes, Terraform, AWS.',
    remoteType: 'remote',
    employmentType: 'full_time',
    salaryMin: 75000,
    salaryMax: 110000,
    currency: 'USD',
    categoryId: 'cat-eng',
    createdAt: daysAgo(100),
    updatedAt: daysAgo(15),
  },
];

export const PREVIEW_APPLICATIONS = [
  {
    id: 'preview-app-1',
    jobId: 'preview-job-1',
    jobTitle: 'Senior Backend Engineer',
    submittedAt: daysAgo(1),
    candidateName: 'Ama Osei',
    email: 'ama@example.com',
    phone: '+233 54 357 9090',
    source: 'Careers website',
    status: 'interview',
    coverLetter: 'I have led backend teams for six years and am excited about your platform work.',
    resumeUrl: 'https://example.com/resume-ama.pdf',
  },
  {
    id: 'preview-app-2',
    jobId: 'preview-job-1',
    jobTitle: 'Senior Backend Engineer',
    submittedAt: daysAgo(3),
    candidateName: 'Kwesi Mensah',
    email: 'kwesi@example.com',
    phone: '+233 20 551 4821',
    source: 'Careers website',
    status: 'shortlisted',
    coverLetter: 'Strong distributed systems background with Go and Kubernetes.',
    resumeUrl: 'https://example.com/resume-kwesi.pdf',
  },
  {
    id: 'preview-app-3',
    jobId: 'preview-job-2',
    jobTitle: 'AI Engineer',
    submittedAt: daysAgo(2),
    candidateName: 'Rosa Kim',
    email: 'rosa@example.com',
    phone: '+1 415 555 0192',
    source: 'LinkedIn',
    status: 'reviewing',
    coverLetter: 'Built NLP pipelines in production at scale.',
    resumeUrl: 'https://example.com/resume-rosa.pdf',
  },
  {
    id: 'preview-app-4',
    jobId: 'preview-job-2',
    jobTitle: 'AI Engineer',
    submittedAt: daysAgo(5),
    candidateName: 'James Okonkwo',
    email: 'james@example.com',
    phone: '',
    source: 'Careers website',
    status: 'submitted',
    coverLetter: '',
    resumeUrl: 'https://example.com/resume-james.pdf',
  },
  {
    id: 'preview-app-5',
    jobId: 'preview-job-1',
    jobTitle: 'Senior Backend Engineer',
    submittedAt: daysAgo(8),
    candidateName: 'Priya Sharma',
    email: 'priya@example.com',
    phone: '+91 98 7654 3210',
    source: 'Referral',
    status: 'hired',
    coverLetter: 'Previously scaled payment systems at a fintech startup.',
    resumeUrl: 'https://example.com/resume-priya.pdf',
  },
  {
    id: 'preview-app-6',
    jobId: 'preview-job-2',
    jobTitle: 'AI Engineer',
    submittedAt: daysAgo(4),
    candidateName: 'Tom Becker',
    email: 'tom@example.com',
    phone: '+49 30 1234567',
    source: 'Careers website',
    status: 'rejected',
    coverLetter: 'Interested in your computer vision roadmap.',
    resumeUrl: '',
  },
  {
    id: 'preview-app-7',
    jobId: 'preview-job-1',
    jobTitle: 'Senior Backend Engineer',
    submittedAt: daysAgo(0),
    candidateName: 'Elena Vasquez',
    email: 'elena@example.com',
    phone: '+34 612 345 678',
    source: 'Careers website',
    status: 'submitted',
    coverLetter: 'Full-stack engineer transitioning to backend platform roles.',
    resumeUrl: 'https://example.com/resume-elena.pdf',
  },
  {
    id: 'preview-app-8',
    jobId: 'preview-job-2',
    jobTitle: 'AI Engineer',
    submittedAt: daysAgo(6),
    candidateName: 'David Chen',
    email: 'david@example.com',
    phone: '+1 206 555 0144',
    source: 'Careers website',
    status: 'interview',
    coverLetter: 'Published research on efficient transformer inference.',
    resumeUrl: 'https://example.com/resume-david.pdf',
  },
];

export const PREVIEW_DASHBOARD = {
  total_applications: PREVIEW_APPLICATIONS.length,
  open_jobs: PREVIEW_JOBS.filter((j) => j.status === 'published').length,
};

export function loadPreviewData() {
  return {
    user: PREVIEW_USER,
    categories: PREVIEW_CATEGORIES,
    jobs: PREVIEW_JOBS.map((j) => ({ ...j })),
    applications: PREVIEW_APPLICATIONS.map((a) => ({ ...a })),
    dashboardStats: { ...PREVIEW_DASHBOARD },
  };
}
